### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by mertserezli** [Vatavuk/excel-io#28]
Statements like MatcherAssert.assertThat can be changed to assertThat by using import static to improve readability and reduce line width.

**Comment by Vatavuk** [comment]
@mertserezli If we use `assertThat` without accompanied class a user will lose visibility from where this method comes from. It also introduces additional complexity if we want to use a method with the same name through some other third-party library.  Although is more verbose, I think using class prefix is cleaner.
